ALTER SESSION SET "_ORACLE_SCRIPT"=true;
BEGIN
   EXECUTE IMMEDIATE 'DROP USER copamundial CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/
CREATE USER copamundial IDENTIFIED BY copamundial;
GRANT CONNECT, RESOURCE, DBA TO copamundial;
ALTER USER copamundial QUOTA UNLIMITED ON USERS;
EXIT;
